
version: 2
models:
    - name: int_localbike_orders_with_cohort
      description: '{{ doc("int_localbike_orders_with_cohort") }}'
      columns:
          - name: cohort_year
            description: "Year of the cohort"
            tests:
                - not_null
          - name: cohort_month
            description: "Month of the cohort"
            tests:
                - not_null
          - name: month_offset
            description: "Offset compared to first order"
          - name: revenue
            description: "Total of orders by cohort"
          - name: active_customers
            description: "Number of customers with an order on the cohort"

    - name: int_localbike_stores
      description: '{{ doc("int_localbike_stores") }}'
      columns:
          - name: store_id
            description: "Unique ID of the store"
            tests:
                - unique
                - not_null
          - name: store_name
            description: "First name of staff"
          - name: city
            description: "City of the store"
          - name: state
            description: "State of the store"
          - name: zip_code
            description: "US Zip Code of the store"
          - name: nb_staff_by_store
            description: "Number of employees by store"
          - name: total_revenue_store
            description: "Total of revenues generated by store"
          - name: volume_sales_by_store
            description: "Total volume of sales generated by the store"
          - name: revenue_store_by_nb_staff
            description: "Revenue of the store divided by number of employees"

    - name: int_localbike_stocks
      description: '{{ doc("int_localbike_stocks") }}'
      columns:
          - name: product_id
            description: "Unique ID of the product"
            tests:
                - unique
                - not_null
          - name: total_revenue_product
            description: "Total revenue of the product"
          - name: stock_product
            description: "Total stock of the product"
          - name: average_stock
            description: "Average stock of all products"

    - name: int_localbike_staffs
      description: '{{ doc("int_localbike_staffs") }}'
      columns:
          - name: staff_id
            description: "Unique ID of the staff"
            tests:
                - unique
                - not_null
          - name: first_name
            description: "First name of staff"
          - name: last_name
            description: "Last name of staff"
          - name: store_id
            description: "ID of the store when the order was created"
            tests:
                - not_null
          - name: manager_id
            description: "ID of the manager of staff"
          - name: total_revenue_staff
            description: "Total revenue generated by staff"
          - name: volume_sales_staff
            description: "Volume of sales generated by staff"

    - name: int_localbike_orders
      description: '{{ doc("int_localbike_orders") }}'
      columns:
          - name: order_id
            description: "Unique ID of the product"
            tests:
                - unique
                - not_null
          - name: total_amount_order
            description: "Total amount of the order"
          - name: customer_id
            description: "ID of the customer who ordered"
            tests:
                - not_null
          - name: order_status
            description: "Status of the order"
          - name: order_created_at
            description: "Date when the order was created"
          - name: store_id
            description: "ID of the store when the order was created"
            tests:
                - not_null
          - name: staff_id
            description: "ID of the staff who completed the order"
            tests:
                - not_null

    - name: int_localbike_products
      description: '{{ doc("int_localbike_products") }}'
      columns:
          - name: product_id
            description: "Unique ID of the order"
            tests:
                - unique
                - not_null
          - name: model_year
            description: "Model Year of the product"
          - name: total_revenue_product
            description: "Revenue of the product"
          - name: total_discount_product
            description: "Total of the discounts of the product in the orders"
          - name: total_revenue_entreprise
            description: "Total of the revenue of the company"
          - name: volume_sales
            description: "Total volume of products sold by the company"
    
    - name: int_localbike_brands
      description: '{{ doc("int_localbike_brands") }}'
      columns:
          - name: brand_id
            description: "Unique ID of the brand"
            tests:
                - unique
                - not_null
          - name: total_revenue_brand
            description: "TotalRevenue of the brand"